[package]
name = "jane-eyre"
version = "0.1.0"
authors = ["Jane Lusby <jlusby@yaah.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = { path = "/home/jlusby/git/rust/eyre" }
tracing-error = { path = "/home/jlusby/git/rust/tracing/tracing-error" }
indenter = { path = "/home/jlusby/git/rust/indenter" }

[dev-dependencies]
tracing = { path = "/home/jlusby/git/rust/tracing/tracing" }
tracing-subscriber = { path = "/home/jlusby/git/rust/tracing/tracing-subscriber", default-features = false, features = ["registry", "fmt"] }
